# NumPy Exercises with Hints

To a some extent, this collection is based on exercises from <https://github.com/rougier/numpy-100> which have been selected by ZI UZH & David Pinezich for the ZI APPD course. The exercises 3-9 have been adapted and their numbering no longer is consistent with the online ressource.

A few hints on how to proceed with the exercises: 
* Use IPython's `?` operator to read documentation on the functions, e.g. `np.any?`
* Try to come up with a naive solution first, and only think about a better solution after, i.e. if you can use any NumPy functions or structs to simplify your code. For example, it's not wrong to try to iterate through an array and change every element in a first version (and yes, there probably is an easier way to do it with NumPy functions)
* Feel free to always ask questions if you're stuck
* Using pen and paper to come up with a solution idea is helpful in a lot of situations
* [google.com](http://www.google.com) and [stackoverflow.com](http://www.stackoverflow.com) are your best buddies while programming


#### 1. Import the numpy package under the name `np` (★☆☆) 


In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'2.0.2'

#### 3.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 4. Create a 5x5 array with random integers (★☆☆) 
(**hint**: np.random.randint)

In [6]:
np.random.randint(0, 9, (5, 5))

array([[8, 1, 6, 2, 6],
       [0, 4, 2, 0, 0],
       [1, 5, 3, 0, 6],
       [2, 2, 7, 4, 1],
       [1, 5, 1, 3, 8]], dtype=int32)

#### 5.  How to get information about the size of an array (★☆☆) 
(**hint**: size, shape)

In [16]:
Z = np.zeros((10,10))
Z.size

100

#### 6.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: Use slicing)

In [17]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [29]:
Y = np.zeros((8,8), dtype=int)
Y[::2, ::2]=1
Y[1::2, 1::2]=1
Y

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 8. Normalize a 10x10 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [40]:
Q = np.random.random((10,10))
print(Q)
print(Q.mean())
print(Q.std())
R = (Q - Q.mean())/Q.std()
R

[[3.94759896e-01 3.24746266e-01 6.27573910e-01 1.74447697e-01
  9.70317174e-01 3.68116693e-01 5.44204691e-01 5.19777245e-01
  9.99839968e-01 2.91597694e-01]
 [6.70021338e-01 6.67240820e-01 3.08903943e-01 8.19427582e-01
  9.27567081e-01 8.50327637e-01 4.64767821e-01 3.04983334e-01
  8.56826950e-01 1.08694634e-01]
 [9.10124002e-01 5.27493904e-01 9.44299386e-01 2.45382360e-01
  3.05795790e-02 2.51084271e-01 6.24294869e-01 6.27538090e-01
  8.76917497e-01 9.10447824e-01]
 [4.04642969e-01 8.12292459e-01 1.63420431e-01 1.54946106e-01
  8.07299852e-01 4.61080568e-01 6.24934036e-01 6.80161289e-01
  1.58723891e-02 4.84017906e-02]
 [3.45775872e-01 9.62532038e-02 3.08138897e-01 2.89970905e-01
  9.91178568e-01 1.55179773e-02 1.75909629e-01 6.81697140e-01
  1.68880896e-01 9.54539160e-01]
 [9.99415360e-01 2.52194734e-01 5.22044143e-01 6.33854859e-02
  8.42371433e-01 9.62677360e-01 8.15508686e-02 5.80070075e-01
  2.36191192e-01 9.00970456e-01]
 [2.33895886e-01 5.21676045e-02 7.05775896e-01 3.02674417e

array([[-0.34697219, -0.56759787,  0.38666711, -1.04121599,  1.46671346,
        -0.43092976,  0.12395554,  0.04698022,  1.55974516, -0.67205505],
       [ 0.52042668,  0.51166476, -0.61751991,  0.99123292,  1.33200015,
         1.08860461, -0.12636448, -0.62987446,  1.10908513, -1.24841585],
       [ 1.27703383,  0.07129681,  1.38472668, -0.81768797, -1.49457059,
        -0.79972021,  0.37633425,  0.38655423,  1.1723941 ,  1.27805425],
       [-0.31582883,  0.96874885, -1.07596491, -1.10266905,  0.95301624,
        -0.13798369,  0.37834839,  0.5523795 , -1.54091562, -1.43840956],
       [-0.50132976, -1.28762106, -0.61993071, -0.67718135,  1.53245151,
        -1.54203244, -1.03660918,  0.55721925, -1.058758  ,  1.41699407],
       [ 1.55840714, -0.79622094,  0.05412362, -1.39119322,  1.06353317,
         1.44263902, -1.33395079,  0.23697389, -0.84665101,  1.24818935],
       [-0.85388394, -1.4265428 ,  0.63309579, -0.63715028,  1.52469507,
        -0.86389483, -0.9025621 , -0.77187416

#### 9. With the help of Boolean masking, replace in a 10x10 array of random integers the numbers (★☆☆) 

* which are not divisible by 3 with the number 555
* which are higher than the mean and divisible by 7 with the number 111

(**hint**: Use the modulo operator)


In [58]:
A = np.random.randint(1,100,(10,10))
print(A)


[[37 69 31 27 40 60 34 78 48 70]
 [61 40 10  4 25  7 36 50 54 39]
 [69 10 20 19 58 70 89 12 39 24]
 [94 44 14 90 78 91 18 48 56 68]
 [ 9 25 92 90 58 31 24 22 43 39]
 [48 44 49 77 86 26 20 13 36 81]
 [32 97 80 21 65 66 11 38 66 47]
 [89 17 45 63 28 28 83  9 67 21]
 [77 94 10 12 64 42 54 12 36  4]
 [53 35 92 29 75 74 91 15 45 41]]


In [56]:
A[A%3 == 0] = 555
A

array([[ 73,  31,  71,  79,  56, 555,  76,  71,  55,  74],
       [555,  64,  55, 555,   2,  67,  29,  14,  49,  14],
       [ 74,  34,  70,   7, 555,  85, 555,  97, 555,  52],
       [555,  13,   2, 555, 555,  97,  16,  32, 555,   4],
       [ 19,  55,  85, 555,   2,  70,  22,  53, 555,  86],
       [ 40,  52, 555, 555,  14, 555, 555, 555,   8,  86],
       [ 79, 555,  74, 555,  16, 555, 555,  70,  22,  50],
       [ 46,  68,  91,  80,  10,  86, 555, 555,  82,  65],
       [ 98,  76,  59, 555, 555,  55, 555, 555,  29, 555],
       [ 47,  71, 555,  74,  74, 555,  94,  41,  13,   2]], dtype=int32)

In [61]:
print(A.mean())
B = A[A > A.mean()]
B
A[(A%7 == 0) & (A>A.mean())] = 111
A

50.27


array([[ 37,  69,  31,  27,  40,  60,  34,  78,  48, 111],
       [ 61,  40,  10,   4,  25,   7,  36,  50,  54,  39],
       [ 69,  10,  20,  19,  58, 111,  89,  12,  39,  24],
       [ 94,  44,  14,  90,  78, 111,  18,  48, 111,  68],
       [  9,  25,  92,  90,  58,  31,  24,  22,  43,  39],
       [ 48,  44, 111, 111,  86,  26,  20,  13,  36,  81],
       [ 32,  97,  80,  21,  65,  66,  11,  38,  66,  47],
       [ 89,  17,  45, 111,  28,  28,  83,   9,  67,  21],
       [111,  94,  10,  12,  64,  42,  54,  12,  36,   4],
       [ 53,  35,  92,  29,  75,  74, 111,  15,  45,  41]], dtype=int32)

## Bonus exercises, a bit more difficult and just for fun.

Selected examples from <https://github.com/rougier/numpy-100>.


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [4]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

#### 39. Create an array with values ranging from 0 to 1 and elements inbetween which are spaced 0.1 (★★☆) 
(**hint**: np.linspace)

#### 40. Create a random array of size 10 and sort it (★★☆) 
(**hint**: sort)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

#### 50. How to find the closest value (to a given scalar) in a vector to another given value? (★★☆)

(**hint**: argmin)

In [4]:
Z = np.arange(100)
v = np.random.uniform(0,100)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [4]:
X = np.random.rand(5, 10)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [4]:
Z = np.random.randint(0,10,(3,3))

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [4]:
Z = np.random.randint(0,3,(3,10))

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [4]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)