# Numpy recap: Quick demo

In [1]:
import numpy as np

Create a numpy array:

In [2]:
twodim = np.random.random((30, 5))
onedim = np.arange(1,20,1)

In [7]:
twodim

array([[0.61103982, 0.30700582, 0.51392215, 0.43014997, 0.34129542],
       [0.46033511, 0.46058222, 0.18278619, 0.46548453, 0.61696602],
       [0.60016954, 0.24188474, 0.43857864, 0.9384252 , 0.75626154],
       [0.98451491, 0.10897033, 0.66722247, 0.95229766, 0.70340876],
       [0.54806834, 0.41414287, 0.35863101, 0.88059017, 0.99876987],
       [0.34150996, 0.78752954, 0.6041281 , 0.42167213, 0.01391645],
       [0.60193719, 0.38989367, 0.38370344, 0.79495032, 0.75235194],
       [0.24454252, 0.81237565, 0.0895513 , 0.82197873, 0.9347351 ],
       [0.97909257, 0.40670622, 0.07617212, 0.38958183, 0.00872384],
       [0.81241088, 0.8227316 , 0.1436528 , 0.45938256, 0.7011258 ],
       [0.74782159, 0.94321407, 0.72344818, 0.7483353 , 0.80046485],
       [0.2848718 , 0.36852783, 0.09755666, 0.7843404 , 0.32510581],
       [0.99031213, 0.88588455, 0.31723925, 0.66781687, 0.80068182],
       [0.80267168, 0.71451623, 0.26150059, 0.38454546, 0.55863792],
       [0.04484583, 0.50296499, 0.

Explore attributes:

In [6]:
print(twodim.ndim)
print(twodim.size)
twodim.shape

2
150


(30, 5)

Access elements:

In [8]:
onedim[2]

np.int64(3)

In [9]:
twodim[(1,1)]

np.float64(0.46058221777918895)

Slicing:

In [11]:
onedim[0:10:2]

array([1, 3, 5, 7, 9])

In [12]:
twodim[2:4:,4::]

array([[0.75626154],
       [0.70340876]])

Ufuncs / aggregates

In [17]:
%timeit multiplied = np.multiply(onedim, 2)

541 ns ± 7.52 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
%timeit multiplied = onedim*2

535 ns ± 5.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
multiplied

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [20]:
np.sum(twodim, axis=1)

array([2.20341318, 2.18615406, 2.97531966, 3.41641413, 3.20020226,
       2.16875617, 2.92283655, 2.9031833 , 1.86027658, 2.93930364,
       3.96328399, 1.8604025 , 3.66193462, 2.72187187, 1.73280994,
       3.29577639, 1.78633106, 2.04388986, 3.47366821, 2.61889613,
       2.6511315 , 2.8126096 , 2.61647182, 3.34838054, 3.0036251 ,
       3.12794193, 2.38779957, 2.80913408, 2.17262822, 2.68897007])

In [13]:
%timeit sum(twodim)
%timeit np.sum(twodim)

10.4 μs ± 75.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.27 μs ± 17.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Boolean masks:

In [21]:
onedim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
onedim < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False])

In [26]:
selected = onedim[(onedim>3)&(onedim<14)]
selected

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])